### ISSUE TITLE
Post-detail social media

### ISSUE THREAD

**Issue by CodeFluent** [gastate/dalnfrontend#59]
Do facebook, twitter, and email for now.

**Comment by CodeFluent** [comment]
twitter completed in 48e9187cc035416fff9a9f12149aa01f0e8c7a1f

**Comment by CodeFluent** [comment]
Completed all social media links, footer facebook still nonfunctional however.

**Comment by Polyergic** [comment]
@lkitto changed (removed?) facebook footer as part of making things less horribly slow
