### ISSUE TITLE
Add Soundcloud Embedded Player

### ISSUE THREAD

**Issue by lkitto** [gastate/dalnfrontend#7]
Utilize the SoundCloud API for this

<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/207534343&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>

**Comment by CodeFluent** [comment]
Completed audio embeds in e63aa79b51964a732b6c4e5b31ca53d840b4191a.

For now it works with our one example in the API, but will check to see if other similar audio embeds work.
